image: docker:19.03.8

pipelines:
    branches:
        master:
            - step:
                name: Deploy to Prod
                services:
                    - docker
                script:
                    - apk update && apk add make && apk add openssh
                    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
                    - make build-image TAG=$BITBUCKET_BUILD_NUMBER
                    - make push-image  TAG=$BITBUCKET_BUILD_NUMBER

