version: "3.7"

services: 
    app:
        container_name: catalog-service
        build: .
        ports: 
            - "3000:3000"
        links:
            - mongo
        environment:
            NODE_ENV: dev
    mongo:
        container_name: catalog-mongo
        image: mongo
        volumes: 
            - mongodata:/data/db
        ports: 
            - "27017:27017"
volumes:
    mongodata:

